package com.fmg.conmon.model;

public class EventModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.AREA
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.EQUIPID
     *
     * @mbggenerated
     */
    private String equipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.COMPONENTNAME
     *
     * @mbggenerated
     */
    private String componentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.COMPONENTTYPE
     *
     * @mbggenerated
     */
    private String componenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.CONMONTYPE
     *
     * @mbggenerated
     */
    private String conmontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.SEVERITY
     *
     * @mbggenerated
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVENT.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.ID
     *
     * @return the value of EVENT.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.ID
     *
     * @param id the value for EVENT.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.AREA
     *
     * @return the value of EVENT.AREA
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.AREA
     *
     * @param area the value for EVENT.AREA
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.EQUIPID
     *
     * @return the value of EVENT.EQUIPID
     *
     * @mbggenerated
     */
    public String getEquipid() {
        return equipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.EQUIPID
     *
     * @param equipid the value for EVENT.EQUIPID
     *
     * @mbggenerated
     */
    public void setEquipid(String equipid) {
        this.equipid = equipid == null ? null : equipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.COMPONENTNAME
     *
     * @return the value of EVENT.COMPONENTNAME
     *
     * @mbggenerated
     */
    public String getComponentname() {
        return componentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.COMPONENTNAME
     *
     * @param componentname the value for EVENT.COMPONENTNAME
     *
     * @mbggenerated
     */
    public void setComponentname(String componentname) {
        this.componentname = componentname == null ? null : componentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.COMPONENTTYPE
     *
     * @return the value of EVENT.COMPONENTTYPE
     *
     * @mbggenerated
     */
    public String getComponenttype() {
        return componenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.COMPONENTTYPE
     *
     * @param componenttype the value for EVENT.COMPONENTTYPE
     *
     * @mbggenerated
     */
    public void setComponenttype(String componenttype) {
        this.componenttype = componenttype == null ? null : componenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.CONMONTYPE
     *
     * @return the value of EVENT.CONMONTYPE
     *
     * @mbggenerated
     */
    public String getConmontype() {
        return conmontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.CONMONTYPE
     *
     * @param conmontype the value for EVENT.CONMONTYPE
     *
     * @mbggenerated
     */
    public void setConmontype(String conmontype) {
        this.conmontype = conmontype == null ? null : conmontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.SEVERITY
     *
     * @return the value of EVENT.SEVERITY
     *
     * @mbggenerated
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.SEVERITY
     *
     * @param severity the value for EVENT.SEVERITY
     *
     * @mbggenerated
     */
    public void setSeverity(String severity) {
        this.severity = severity == null ? null : severity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVENT.STATUS
     *
     * @return the value of EVENT.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVENT.STATUS
     *
     * @param status the value for EVENT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}