package com.fmg.conmon.dao.impl;

import com.fmg.conmon.model.EventModel;
import com.fmg.conmon.model.EventModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int countByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int deleteByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int insert(EventModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int insertSelective(EventModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    List<EventModel> selectByExample(EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    EventModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EventModel record, @Param("example") EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EventModel record, @Param("example") EventModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventModel record);
}