  /********* Begin Procedure Script ************/ 
 BEGIN 
    /** RESRCE INFO **/
    
 	var_resource=SELECT 
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	B.RESOURCE_TYPE,
 	A.DESCRIPTION AS RESRCE_NAME
	FROM MHP.RESRCE AS A,MHP.RESOURCE_TYPE AS B,MHP.RESOURCE_TYPE_RESOURCE AS C
	WHERE A.HANDLE=C.RESOURCE_BO AND B.HANDLE=C.RESOURCE_TYPE_BO
	AND A.SITE = :site_in
	AND A.WORK_AREA = :work_center_in
	AND B.ENABLED = 'true';
	
	
	/**FILTER LINE **/
 	/**var_resource = APPLY_FILTER(:var_resource, :line_in);**/
 	/**FILTER RESOURCE_TYPE **/
 	/**var_resource = APPLY_FILTER(:var_resource, :resource_type_in);**/
	/**FILTER RESRCE **/
 	var_resource = APPLY_FILTER(:var_resource, :resrce_in);
 	
 	IF line_in !='' THEN
		 	var_resource= SELECT
				 	A.SITE,
				 	A.HANDLE,
				 	A.WORK_AREA,
				 	A.LINE_AREA,
				 	A.RESRCE,
				 	A.RESOURCE_TYPE,
				 	A.RESRCE_NAME
		 	FROM :var_resource AS A
		 	WHERE A.LINE_AREA=:line_in;
 	END IF;
 	 	IF resource_type_in !='' THEN
		 	 var_resource=SELECT 
				 	A.SITE,
				 	A.HANDLE,
				 	A.WORK_AREA,
				 	A.LINE_AREA,
				 	A.RESRCE,
				 	A.RESOURCE_TYPE,
				 	A.RESRCE_NAME
		 	FROM :var_resource AS A
		 	WHERE A.RESOURCE_TYPE=:resource_type_in;
 	END IF;
 	/**
 	 	IF resrce_in !='' THEN
		 	 var_resource=SELECT
				 	SITE,
				 	HANDLE,
				 	WORK_AREA,
				 	LINE_AREA,
				 	RESRCE,
				 	RESOURCE_TYPE,
				 	RESRCE_NAME
		 	FROM :var_resource
		 	WHERE RESRCE IN ()
 	END IF;
 	**/
 	
 	/** RESRCE SHIFT INFO **/
	var_resrce_shift = SELECT 
	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	B.DESCRIPTION AS WORK_AREA_DES,
 	MIN(C.START_TIME) AS START_TIME
	FROM :var_resource AS A
	LEFT JOIN MHP.WORK_CENTER AS B 
	ON A.SITE = B.SITE AND A.WORK_AREA = B.WORK_CENTER
	LEFT JOIN MHP.WORK_CENTER_SHIFT AS C
	ON B.HANDLE = C.WORK_CENTER_BO
	WHERE B.ENABLED='true' 
	AND C.ENABLED='true'
	GROUP BY A.SITE, A.HANDLE, A.WORK_AREA, A.LINE_AREA, A.RESRCE, A.RESRCE_NAME,B.DESCRIPTION;

	/**当starttime为null,设置为 08:00:00  **/
	var_resrce_shift_time = SELECT 
	SITE,
 	HANDLE,
 	WORK_AREA,
 	LINE_AREA,
 	RESRCE,
 	RESRCE_NAME,
 	WORK_AREA_DES,
 	CASE WHEN START_TIME IS NULL OR START_TIME = '' THEN '08:00:00' ELSE START_TIME END AS START_TIME
 	FROM :var_resrce_shift;
 	
 	/**现在时间在 0点到START_TIME的最小值之间 ,日期取前一天**/
 	var_resrce_current_date = SELECT 
	SITE,
 	HANDLE,
 	WORK_AREA,
 	LINE_AREA,
 	RESRCE,
 	RESRCE_NAME,
 	WORK_AREA_DES,
 	START_TIME,
 	CASE WHEN CURRENT_TIME > '00:00:00' AND CURRENT_TIME < START_TIME THEN ADD_DAYS(CURRENT_DATE,-1) ELSE CURRENT_DATE END AS CUR_DATE
 	FROM :var_resrce_shift;
 	
 	
 	/**当前日期   + 时间 **/
 	var_resrce_shift_date_time = SELECT 
 	SITE,
 	HANDLE,
 	WORK_AREA,
 	LINE_AREA,
 	RESRCE,
 	RESRCE_NAME,
 	WORK_AREA_DES,
 	START_TIME,
 	CAST(CAST(CUR_DATE AS NVARCHAR) || ' ' || CAST(START_TIME AS NVARCHAR) AS SECONDDATE) AS DATE_TIME
 	FROM :var_resrce_current_date;
	
	/** 设备取拉线描述  **/
	var_resrce_line_desc = SELECT 
	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.WORK_AREA_DES,
 	A.START_TIME,
 	A.DATE_TIME,
 	B.DESCRIPTION AS LINE_AREA_DES
 	FROM :var_resrce_shift_date_time AS A
 	LEFT JOIN MHP.WORK_CENTER AS B
 	ON  A.SITE = B.SITE 
 	AND A.LINE_AREA = B.WORK_CENTER
 	WHERE B.ENABLED = 'true';
 	
 	
	/**设备 关联设备log  可能会关联到多条log**/	
 	var_resource_time_log=SELECT
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	B.RESOURCE_STATE,
	--B.START_DATE_TIME,
	row_number() over(PARTITION BY A.HANDLE ORDER BY B.START_DATE_TIME DESC) AS ORDER_QTY
 	FROM :var_resrce_line_desc AS A 
 	LEFT JOIN MHP.RESOURCE_TIME_LOG AS B 
 	ON A.SITE=B.SITE
 	AND A.HANDLE=B.RESOURCE_BO
 	AND B.START_DATE_TIME <= CURRENT_TIMESTAMP
 	AND B.END_DATE_TIME IS NULL;
 	
 	/**设备 关联设备log 得最大一条的log**/
 	var_resource_log_filter=SELECT
 	SITE,
 	HANDLE,
 	WORK_AREA,
 	LINE_AREA,
 	RESRCE,
 	RESRCE_NAME,
 	DATE_TIME,
	LINE_AREA_DES,
	WORK_AREA_DES,
	RESOURCE_STATE
	--START_DATE_TIME
 	FROM :var_resource_time_log
 	WHERE ORDER_QTY = 1;
	
	/**设备 关联设备状态**/	
 	var_resource_state=SELECT 
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	B.DESCRIPTION AS RESOURCE_STATE_DES,
	B.STATE AS RESOURCE_STATE
 	FROM :var_resource_log_filter AS A
 	LEFT JOIN MHP.RESOURCE_STATE AS B
 	ON A.RESOURCE_STATE=B.STATE
 	AND A.SITE=B.SITE;
 	
 	/**设备 关联PPM **/
 	var_resource_ppm = SELECT 
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	A.RESOURCE_STATE_DES,
	A.RESOURCE_STATE,
	B.REALTIME_PPM
 	FROM :var_resource_state AS A
 	LEFT JOIN MHP.REALTIME_PPM AS B
 	ON A.HANDLE = B.RESOURCE_BO;
 
 	/**设备 关联三色灯 **/
 	var_color=SELECT 
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	A.RESOURCE_STATE_DES,
	A.RESOURCE_STATE,
	A.REALTIME_PPM,
	B.COLOR_LIGHT
 	FROM :var_resource_ppm AS A
 	LEFT JOIN MHP.COLOR_LIGHT AS B 
 	ON A.HANDLE=B.RESOURCE_BO;
 	
 	/** RESOURCE_ALERT_LOG 录取当日累计报警次数 **/
 	var_resource_alert_handle_count=SELECT
 	A.HANDLE,
 	COUNT(A.HANDLE) AS ALERT_COUNT
 	FROM :var_color AS A
 	INNER JOIN MHP.RESOURCE_ALERT_LOG AS B
 	ON  A.SITE=B.SITE
 	AND A.RESRCE=B.RESRCE
 	AND B.DATE_TIME >= A.DATE_TIME
 	AND B.DATE_TIME<= CURRENT_TIMESTAMP
 	GROUP BY A.HANDLE;
 	
 	/** RESRCE 关联  录取当日累计报警次数 **/
 	var_resource_alert_log=SELECT
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	A.RESOURCE_STATE_DES,
	A.RESOURCE_STATE,
	A.REALTIME_PPM,
	A.COLOR_LIGHT,
 	CASE WHEN B.ALERT_COUNT IS NULL THEN 0 ELSE B.ALERT_COUNT END AS ALERT_COUNT
 	FROM :var_color AS A
 	LEFT JOIN :var_resource_alert_handle_count AS B
 	ON A.HANDLE = B.HANDLE;
 	
 	/**RESOURCE_TIME_LOG 录取当日累计停机次数**/
 	var_down_count=SELECT
 	A.HANDLE,
 	COUNT(B.HANDLE) AS HALT_COUNT
 	FROM :var_resource_alert_log AS A
 	INNER JOIN MHP.RESOURCE_TIME_LOG AS B
 	ON A.SITE=B.SITE
 	AND A.HANDLE=B.RESOURCE_BO
 	AND B.RESOURCE_STATE='D'
 	AND( 
 	(B.START_DATE_TIME<=A.DATE_TIME AND B.END_DATE_TIME>A.DATE_TIME AND B.END_DATE_TIME <= CURRENT_TIMESTAMP) 
 	OR (B.START_DATE_TIME<=A.DATE_TIME AND (B.END_DATE_TIME IS NULL OR B.END_DATE_TIME = '') )
 	OR (B.START_DATE_TIME >= A.DATE_TIME and B.END_DATE_TIME <= CURRENT_TIMESTAMP)
 	OR (B.START_DATE_TIME >= A.DATE_TIME and (B.END_DATE_TIME IS NULL OR B.END_DATE_TIME = ''))
 	)
 	GROUP BY A.HANDLE;
 	
 	/**RESRCE 关联当日累计停机次数**/
 	var_down=SELECT 
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
 	A.DATE_TIME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	A.RESOURCE_STATE_DES,
	A.RESOURCE_STATE,
	A.REALTIME_PPM,
	A.COLOR_LIGHT,
 	A.ALERT_COUNT,
 	CASE WHEN B.HALT_COUNT IS NULL THEN 0 ELSE B.HALT_COUNT END AS HALT_COUNT
 	FROM :var_resource_alert_log AS A
 	LEFT JOIN :var_down_count AS B
 	ON A.HANDLE = B.HANDLE;

 	var_out = SELECT
 	A.SITE,
 	A.HANDLE,
 	A.WORK_AREA,
 	A.LINE_AREA,
 	A.RESRCE,
 	A.RESRCE_NAME,
	A.LINE_AREA_DES,
	A.WORK_AREA_DES,
	---A.RESOURCE_STATE_DES as RESOURCE_STATE,
	CASE WHEN A.RESOURCE_STATE_DES IS NULL THEN '' ELSE A.RESOURCE_STATE_DES END AS RESOURCE_STATE,
	--A.REALTIME_PPM,
	CASE WHEN A.REALTIME_PPM IS NULL THEN '' ELSE ROUND(A.REALTIME_PPM,2) || '' END AS REALTIME_PPM,
	A.COLOR_LIGHT,
 	A.ALERT_COUNT,
 	A.HALT_COUNT,
 	1 as QTY,
 	A.DATE_TIME
 	FROM :var_down AS A;
 	
END /********* End Procedure Script ************/